<a href="https://colab.research.google.com/github/YeonKang/Python-for-Machine-Learning/blob/main/Lab2_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
def n_size_ndarray_creation(n, dtype=np.int):
    return np.array(range(n**2),dtype=dtype).reshape(n,n)

In [ ]:
n_size_ndarray_creation(3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    if type==0:
      return np.zeros(shape=shape, dtype=dtype)
    if type==1:
      return np.ones(shape=shape, dtype=dtype)
    if type==99:
      return np.empty(shape=shape, dtype=dtype)

In [ ]:
def change_shape_of_ndarray(X, n_row):
    return X.flatten() if n_row==1 else X.reshape(n_row,-1)

In [ ]:
X = np.ones((32,32),dtype=np.int)
X

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [ ]:
change_shape_of_ndarray(X,1)

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
def concat_ndarray(X_1, X_2, axis):
    try:
      if X_1.ndim == 1:
        X_1 = X_1.reshape(1,-1)
      if X_2.ndim == 1:
        X_2 = X_2.reshape(1,-1)
      return np.concatenate((X_1,X_2),axis=axis)
    except ValueError as e:
      return False

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
concat_ndarray(a,b,1)

False

In [ ]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    X = X.astype(np.float32)
    n_row,n_column = X.shape
    if axis == 99:
      x_mean = np.mean(X)
      x_std = np.std(X)
      Z = (X-x_mean) / x_std
    if axis == 0:
      x_mean = np.mean(X,0).reshape(1,-1)
      x_std = np.std(X,0).reshape(1,-1)
      Z = (X-x_mean) / x_std
    if axis == 1:
      x_mean = np.mean(X,1).reshape(n_row,-1)
      x_std = np.std(X,1).reshape(n_row,-1)
      Z = (X-x_mean) / x_std

      return Z

In [ ]:
X = np.arange(12,dtype=np.float32).reshape(4,3)
normalize_ndarray(X,1)

array([[-1.2247448,  0.       ,  1.2247448],
       [-1.2247448,  0.       ,  1.2247448],
       [-1.2247448,  0.       ,  1.2247448],
       [-1.2247448,  0.       ,  1.2247448]], dtype=float32)

In [ ]:
def save_ndarray(X, filename="test.npy"):
    file_test = open(filename,"wb")
    np.save(X,file_test)

In [2]:
def boolean_index(X, condition):
    condition = eval(str("X")+condition)
    return np.where(condition)

In [3]:
X = np.arange(32,dtype=np.float32)
boolean_index(X,">6")

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31]),)

In [4]:
def find_nearest_value(X, target_value):
    return X[np.argmin(np.abs(X-target_value))]

In [5]:
X= np.random.uniform(0,1,100)
target_value = 0.3
find_nearest_value(X,target_value)

0.29036298679063133

In [6]:
def get_n_largest_values(X, n):
    return X[np.argsort(X[::-1])[:n]]

In [7]:
X = np.random.uniform(0,1,5)
get_n_largest_values(X,3)

array([0.99067058, 0.83349288, 0.23288645])