<a href="https://colab.research.google.com/github/YeonKang/Python-for-Machine-Learning/blob/main/Lec2_1_Numerical_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**import**

In [2]:
import numpy as np

**Array creation**

In [3]:
test_array = np.array([1,4,5,8],float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [5]:
test_array = np.array([1,4,5,"8"],float)
print(test_array)
print(type(test_array[3])) #automatic conversion of string type data "8" to float type 8
print(test_array.dtype) #data type of the entire array
print(test_array.shape) #shape of the entire array -> result "," means data type is tuple & test_array is vector array

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [6]:
test_array = np.array([[1,4,5,8]],float)
print(test_array.shape) #test_array is matrix array

(1, 4)


**Array shape**

In [7]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]]]

In [11]:
np.array(tensor,int).ndim

3

In [10]:
np.array(tensor,int).size #total data size

48

**Array dtype**

In [14]:
np.array([[1,2,3],[4.5,"5","6"]],dtype=np.float32).nbytes #32bits = 4ytes -> 6*4bytes

24

In [15]:
np.array([[1,2,3],[4.5,"5","6"]],dtype=np.int8).nbytes #8bits = 1bytes -> 6*1bytes

6

In [17]:
np.array([[1,2,3],[4.5,"5","6"]],dtype=np.float64).nbytes #64bits = 8bytes -> 6*8bytes

48

**reshape** (total data size is unchanged)

In [18]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [19]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [20]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [21]:
np.array(test_matrix).reshape(-1,2).shape #-1 means elect the number of rows based on size

(4, 2)

In [22]:
np.array(test_matrix).reshape(2,-1).shape #-1 means elect the number of column based on size

(2, 4)

**flatten**

In [23]:
test_matrix = [[[1,2,3,4],[1,2,5,8]],[[1,2,3,4],[1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

**indexing & slicing**

In [24]:
a = np.array([[1,2,3],[4.5,5,6]],int)
print(a)
print(a[0,0])
print(a[0][0])

[[1 2 3]
 [4 5 6]]
1
1


In [25]:
a[0,0] = 12
print(a)

[[12  2  3]
 [ 4  5  6]]


In [26]:
a[0][0] = 5
print(a)

[[5 2 3]
 [4 5 6]]


In [27]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
a[:2,2:] #2 or more rows of all rows

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [28]:
a[1,1:3] #rows 1 to 2 of 1 row

array([7, 8])

In [29]:
a[1:3] #whole of rows 1 and 2

array([[ 6,  7,  8,  9, 10]])