<a href="https://colab.research.google.com/github/YeonKang/Python-for-Machine-Learning/blob/main/Lec2_1_Numerical_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**import**

In [2]:
import numpy as np

**Array creation**

In [3]:
test_array = np.array([1,4,5,8],float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [5]:
test_array = np.array([1,4,5,"8"],float)
print(test_array)
print(type(test_array[3])) #automatic conversion of string type data "8" to float type 8
print(test_array.dtype) #data type of the entire array
print(test_array.shape) #shape of the entire array -> result "," means data type is tuple & test_array is vector array

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [6]:
test_array = np.array([[1,4,5,8]],float)
print(test_array.shape) #test_array is matrix array

(1, 4)


**Array shape**

In [7]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]]]

In [11]:
np.array(tensor,int).ndim

3

In [10]:
np.array(tensor,int).size #total data size

48

**Array dtype**

In [14]:
np.array([[1,2,3],[4.5,"5","6"]],dtype=np.float32).nbytes #32bits = 4ytes -> 6*4bytes

24

In [15]:
np.array([[1,2,3],[4.5,"5","6"]],dtype=np.int8).nbytes #8bits = 1bytes -> 6*1bytes

6

In [17]:
np.array([[1,2,3],[4.5,"5","6"]],dtype=np.float64).nbytes #64bits = 8bytes -> 6*8bytes

48

**reshape** (total data size is unchanged)

In [18]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [19]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [20]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [21]:
np.array(test_matrix).reshape(-1,2).shape #-1 means elect the number of rows based on size

(4, 2)

In [22]:
np.array(test_matrix).reshape(2,-1).shape #-1 means elect the number of column based on size

(2, 4)

**flatten**

In [23]:
test_matrix = [[[1,2,3,4],[1,2,5,8]],[[1,2,3,4],[1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

**indexing & slicing**

In [24]:
a = np.array([[1,2,3],[4.5,5,6]],int)
print(a)
print(a[0,0])
print(a[0][0])

[[1 2 3]
 [4 5 6]]
1
1


In [25]:
a[0,0] = 12
print(a)

[[12  2  3]
 [ 4  5  6]]


In [26]:
a[0][0] = 5
print(a)

[[5 2 3]
 [4 5 6]]


In [27]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
a[:2,2:] #2 or more rows of all rows

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [28]:
a[1,1:3] #rows 1 to 2 of 1 row

array([7, 8])

In [29]:
a[1:3] #whole of rows 1 and 2

array([[ 6,  7,  8,  9, 10]])

**arange** (create a list of values ​​by specifying the range of the array)

In [3]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
np.arange(0,5,0.5) #(start, stop, step)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [6]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

**ones, zeros and empty**

In [8]:
np.zeros(shape=(10,),dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [9]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(shape=(10,),dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [13]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.empty(shape=(10,),dtype=np.int8) #do not initialize memory

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [14]:
np.empty((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**something_like**

In [16]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

**identity** (generate identity matrix I)

In [17]:
np.identity(n=3,dtype=np.int8) #n = number of rows

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [18]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**eye** (generate diagonal matrix)

In [19]:
np.eye(N=3,M=5,dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(3,5,k=2) #k = start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**diag** (extract values ​​of diagonal matrix)

In [22]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [23]:
np.diag(matrix,k=1) #k = start index

array([1, 5])

**random sampling**

In [24]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.92019095, 0.87201147, 0.61561253, 0.38043557, 0.61538889],
       [0.11798245, 0.25585745, 0.58703176, 0.17673455, 0.6519718 ]])

In [25]:
np.random.normal(0,1,10).reshape(2,5)

array([[ 1.46453207,  1.27836673, -0.17022136,  0.05990039, -0.73196801],
       [ 0.69604784, -0.6146197 , -0.45605249, -0.05338702, -0.29631789]])

**sum**

In [27]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
test_array.sum(dtype=np.float)

55.0

**axis** (when a new matrix element is created, the index of the element becomes 0, and the indexes of the previously created elements must be pushed back by 1 to add 1)

In [29]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
test_array.sum(axis=1), test_array.sum(axis=0) #axis=1 -> column, axis=0 -> row

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [31]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [33]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [34]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [35]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

**mean & std**

In [37]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
test_array.mean(), test_array.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

In [40]:
test_array.std(), test_array.std(axis=0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

**concatenate**

In [41]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b)) #vertical

array([[1, 2, 3],
       [2, 3, 4]])

In [42]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b)) #horizontal

array([[1, 2],
       [2, 3],
       [3, 4]])

In [43]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [44]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T),axis=1) #T = transposition

array([[1, 2, 5],
       [3, 4, 6]])

**operations b/t arrays**

In [45]:
test_a = np.array([[1,2,3],[4,5,6]],float)

In [46]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [47]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

**Dot product**

In [49]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [50]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

**transpose**

In [51]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

**broadcasting**

In [55]:
test_matrix = np.array([[1,2,3],[4,5,6]],float)
scalar = 3

In [56]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [57]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [58]:
test_matrix // scalar

array([[0., 0., 1.],
       [1., 1., 2.]])

In [60]:
test_matrix * scalar

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [61]:
test_matrix / scalar

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [59]:
test_matrix ** scalar

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])