<a href="https://colab.research.google.com/github/YeonKang/Python-for-Machine-Learning/blob/main/Lec2_1_Numerical_Python_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**import**

In [1]:
import numpy as np

**Array creation**

In [ ]:
test_array = np.array([1,4,5,8],float)
print(test_array)
type(test_array[3])

[1. 4. 5. 8.]


numpy.float64

In [ ]:
test_array = np.array([1,4,5,"8"],float)
print(test_array)
print(type(test_array[3])) #automatic conversion of string type data "8" to float type 8
print(test_array.dtype) #data type of the entire array
print(test_array.shape) #shape of the entire array -> result "," means data type is tuple & test_array is vector array

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [ ]:
test_array = np.array([[1,4,5,8]],float)
print(test_array.shape) #test_array is matrix array

(1, 4)


**Array shape**

In [ ]:
tensor = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]],[[1,2,5,8],[1,2,5,8],[1,2,5,8]]]

In [ ]:
np.array(tensor,int).ndim

3

In [ ]:
np.array(tensor,int).size #total data size

48

**Array dtype**

In [ ]:
np.array([[1,2,3],[4.5,"5","6"]],dtype=np.float32).nbytes #32bits = 4ytes -> 6*4bytes

24

In [ ]:
np.array([[1,2,3],[4.5,"5","6"]],dtype=np.int8).nbytes #8bits = 1bytes -> 6*1bytes

6

In [ ]:
np.array([[1,2,3],[4.5,"5","6"]],dtype=np.float64).nbytes #64bits = 8bytes -> 6*8bytes

48

**reshape** (total data size is unchanged)

In [ ]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [ ]:
np.array(test_matrix).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [ ]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [ ]:
np.array(test_matrix).reshape(-1,2).shape #-1 means elect the number of rows based on size

(4, 2)

In [ ]:
np.array(test_matrix).reshape(2,-1).shape #-1 means elect the number of column based on size

(2, 4)

**flatten**

In [ ]:
test_matrix = [[[1,2,3,4],[1,2,5,8]],[[1,2,3,4],[1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

**indexing & slicing**

In [ ]:
a = np.array([[1,2,3],[4.5,5,6]],int)
print(a)
print(a[0,0])
print(a[0][0])

[[1 2 3]
 [4 5 6]]
1
1


In [ ]:
a[0,0] = 12
print(a)

[[12  2  3]
 [ 4  5  6]]


In [ ]:
a[0][0] = 5
print(a)

[[5 2 3]
 [4 5 6]]


In [ ]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
a[:2,2:] #2 or more rows of all rows

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [ ]:
a[1,1:3] #rows 1 to 2 of 1 row

array([7, 8])

In [ ]:
a[1:3] #whole of rows 1 and 2

array([[ 6,  7,  8,  9, 10]])

**arange** (create a list of values ​​by specifying the range of the array)

In [ ]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
np.arange(0,5,0.5) #(start, stop, step)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

**ones, zeros and empty**

In [ ]:
np.zeros(shape=(10,),dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [ ]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(10,),dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [ ]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.empty(shape=(10,),dtype=np.int8) #do not initialize memory

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [ ]:
np.empty((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**something_like**

In [ ]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

**identity** (generate identity matrix I)

In [ ]:
np.identity(n=3,dtype=np.int8) #n = number of rows

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**eye** (generate diagonal matrix)

In [ ]:
np.eye(N=3,M=5,dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3,5,k=2) #k = start index

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**diag** (extract values ​​of diagonal matrix)

In [ ]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [ ]:
np.diag(matrix,k=1) #k = start index

array([1, 5])

**random sampling**

In [ ]:
np.random.uniform(0,1,10).reshape(2,5)

array([[0.92019095, 0.87201147, 0.61561253, 0.38043557, 0.61538889],
       [0.11798245, 0.25585745, 0.58703176, 0.17673455, 0.6519718 ]])

In [ ]:
np.random.normal(0,1,10).reshape(2,5)

array([[ 1.46453207,  1.27836673, -0.17022136,  0.05990039, -0.73196801],
       [ 0.69604784, -0.6146197 , -0.45605249, -0.05338702, -0.29631789]])

**sum**

In [ ]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
test_array.sum(dtype=np.float)

55.0

**axis** (when a new matrix element is created, the index of the element becomes 0, and the indexes of the previously created elements must be pushed back by 1 to add 1)

In [ ]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
test_array.sum(axis=1), test_array.sum(axis=0) #axis=1 -> column, axis=0 -> row

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [ ]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [ ]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [ ]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [ ]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

**mean & std**

In [ ]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
test_array.mean(), test_array.mean(axis=0)

(6.5, array([5., 6., 7., 8.]))

In [ ]:
test_array.std(), test_array.std(axis=0)

(3.452052529534663, array([3.26598632, 3.26598632, 3.26598632, 3.26598632]))

**concatenate**

In [ ]:
a = np.array([1,2,3])
b = np.array([2,3,4])
np.vstack((a,b)) #vertical

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b)) #horizontal

array([[1, 2],
       [2, 3],
       [3, 4]])

In [ ]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b),axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T),axis=1) #T = transposition

array([[1, 2, 5],
       [3, 4, 6]])

**operations b/t arrays**

In [ ]:
test_a = np.array([[1,2,3],[4,5,6]],float)

In [ ]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [ ]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
test_a * test_a

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

**Dot product**

In [ ]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [ ]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

**transpose**

In [ ]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

**broadcasting**

In [ ]:
test_matrix = np.array([[1,2,3],[4,5,6]],float)
scalar = 3

In [ ]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [ ]:
test_matrix // scalar

array([[0., 0., 1.],
       [1., 1., 2.]])

In [ ]:
test_matrix * scalar

array([[ 3.,  6.,  9.],
       [12., 15., 18.]])

In [ ]:
test_matrix / scalar

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [ ]:
test_matrix ** scalar

array([[  1.,   8.,  27.],
       [ 64., 125., 216.]])

**Numpy performance #1**

In [3]:
def scalar_vector_product(scalar,vector):
  result = []
  for value in vector:
    result.append(scalar*value)
  return result

iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

%timeit scalar_vector_product(scalar,vector) #for loop
%timeit [scalar*value for value in range(iternation_max)] #list comprehension
%timeit np.arange(iternation_max)*scalar #numpy

1 loop, best of 3: 11.2 s per loop
1 loop, best of 3: 9 s per loop
1 loop, best of 3: 237 ms per loop


**All & Any**

In [64]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.all(a>5), np.all(a<10) #similar as AND

(False, True)

In [66]:
np.any(a>5), np.any(a<0) #similar as OR

(True, False)

**Comparison operation**

In [9]:
test_a = np.array([1,3,0],float)
test_b = np.array([5,2,1],float)
test_a == test_b

array([False, False, False])

In [10]:
test_a > test_b

array([False,  True, False])

In [11]:
(test_a > test_b).any()

True

In [3]:
a = np.array([1,3,0],float)
np.logical_and(a>0,a<3) #AND condition

array([ True, False, False])

In [13]:
b = np.array([True,False,True],bool)
np.logical_not(b) #NOT condition

array([False,  True, False])

In [14]:
c = np.array([False,True,False],bool)
np.logical_or(b,c) #OR condition

array([ True,  True,  True])

**np.where**

In [6]:
a = np.array([1,3,0],float)
np.where(a>0,3,2) #where(condition,TRUE,FALSE)

array([3, 3, 2])

In [5]:
a = np.arange(10)
np.where(a>5)

(array([6, 7, 8, 9]),)

In [7]:
a = np.array([1,np.NaN,np.Inf],float)
np.isnan(a)

array([False,  True, False])

In [8]:
np.isfinite(a)

array([ True, False, False])

**argmax & argmin**

In [9]:
a = np.array([1,2,4,5,8,78,23,3])
np.argmax(a), np.argmin(a)

(5, 0)

In [10]:
a = np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a,axis=1), np.argmin(a,axis=0)

(array([3, 1, 1]), array([0, 0, 2, 2]))

**boolean index**

In [11]:
test_array = np.array([1,4,0,2,3,8,9,7],float)
test_array>3

array([False,  True, False, False, False,  True,  True,  True])

In [12]:
test_array[test_array>3]

array([4., 8., 9., 7.])

In [13]:
condition = test_array<3
test_array[condition]

array([1., 0., 2.])

**fancy index**

In [14]:
a = np.array([2,4,6,8],float)
b = np.array([0,0,1,3,2,1],int) #must be declared as integer
a[b] #bracket index, extract the values ​​of the a array with the value of the b array as index

array([2., 2., 4., 8., 6., 4.])

In [15]:
a.take(b) #same as bracket index

array([2., 2., 4., 8., 6., 4.])

In [16]:
a = np.array([[1,4],[9,16]],float)
b = np.array([0,0,1,1,0],int)
c = np.array([0,0,1,1,0],int)
a[b,c] #extract the values ​​of the a array with the value of the b array as the row index and the c array as the column index

array([ 1.,  1., 16., 16.,  1.])